version: '3.8'

services:
  web:
    build: ./poeserver/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./poeserver/app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    extra_hosts:
      - "dev.poeapp.com:127.0.0.1"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data: