# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
    push:
        branches: [poet]

# Your workflows jobs.
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Check-out your repository.
            - name: Checkout
              uses: actions/checkout@v2

            # Build and deploy
            - name: Build, push, and release Docker to Heroku.
              uses: gonuit/heroku-docker-deploy@v1.3.3
              with:
                  email: jsalaz1989@gmail.com
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: poeserver
                  dockerfile_directory: ./image/app/
                  dockerfile_name: Dockerfile
                  docker_options: "--no-cache --target prod"
                  process_type: web
            - name: Test
              run: python manage.py test
