version: "3.9"

services:
    web:
        image: "server:dev"
        build:
            target: development_build
            context: ./app
            cache_from:
                - "server:dev"
                - "server:latest"
                - "*"
            args:
                DJANGO_ENV: development
            dockerfile: Dockerfile
        command: poetry run python -Wd manage.py runserver --nostatic 0.0.0.0:8000
        volumes:
            - ./app:/code/
            - venv:/code/.venv/ # exclude venv so as not to erase during mount
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db

    db:
        image: postgres:14.0-alpine
        volumes:
            - ./app/data/db:/var/lib/postgresql/data
        restart: unless-stopped
        env_file:
            - ./.env.dev

volumes:
    postgres_data:
    venv:
